# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'visualization_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindowv(object):
    def setupUi(self, MainWindowv):
        MainWindowv.setObjectName("MainWindowv")
        MainWindowv.resize(800, 368)
        MainWindowv.setMinimumSize(QtCore.QSize(800, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setUnderline(False)
        MainWindowv.setFont(font)
        MainWindowv.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindowv.setAutoFillBackground(False)
        MainWindowv.setStyleSheet("background-color: rgb(221, 221, 221);\n"
"color: rgb(13, 13, 13);")
        MainWindowv.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindowv)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("color: rgb(16, 16, 16);")
        self.label.setLineWidth(2)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setStyleSheet("background-color: rgb(211, 255, 224);")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 784, 297))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget_info_show = QtWidgets.QTabWidget(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tabWidget_info_show.setFont(font)
        self.tabWidget_info_show.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabWidget_info_show.setStyleSheet("background-color: rgb(124, 221, 215);\n"
"font: 12pt \"Times New Roman\";")
        self.tabWidget_info_show.setObjectName("tabWidget_info_show")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_7)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.load_class = QtWidgets.QPushButton(self.tab_7)
        self.load_class.setStyleSheet("background-color: rgb(209, 209, 104);")
        self.load_class.setObjectName("load_class")
        self.gridLayout_6.addWidget(self.load_class, 1, 1, 1, 1)
        self.recognit_batch_path = QtWidgets.QLineEdit(self.tab_7)
        self.recognit_batch_path.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.recognit_batch_path.setObjectName("recognit_batch_path")
        self.gridLayout_6.addWidget(self.recognit_batch_path, 3, 3, 1, 1)
        self.recognit_pic = QtWidgets.QPushButton(self.tab_7)
        self.recognit_pic.setStyleSheet("background-color: rgb(209, 209, 104);")
        self.recognit_pic.setObjectName("recognit_pic")
        self.gridLayout_6.addWidget(self.recognit_pic, 2, 1, 1, 1)
        self.load_model = QtWidgets.QPushButton(self.tab_7)
        self.load_model.setStyleSheet("background-color: rgb(209, 209, 104);")
        self.load_model.setObjectName("load_model")
        self.gridLayout_6.addWidget(self.load_model, 0, 1, 1, 1)
        self.recognit_batch = QtWidgets.QPushButton(self.tab_7)
        self.recognit_batch.setStyleSheet("background-color: rgb(209, 209, 104);")
        self.recognit_batch.setObjectName("recognit_batch")
        self.gridLayout_6.addWidget(self.recognit_batch, 3, 1, 1, 1)
        self.load_model_path = QtWidgets.QLineEdit(self.tab_7)
        self.load_model_path.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.load_model_path.setObjectName("load_model_path")
        self.gridLayout_6.addWidget(self.load_model_path, 0, 3, 1, 1)
        self.recognit_pic_path = QtWidgets.QLineEdit(self.tab_7)
        self.recognit_pic_path.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.recognit_pic_path.setObjectName("recognit_pic_path")
        self.gridLayout_6.addWidget(self.recognit_pic_path, 2, 3, 1, 1)
        self.refresh2 = QtWidgets.QPushButton(self.tab_7)
        self.refresh2.setStyleSheet("background-color: rgb(209, 209, 104);")
        self.refresh2.setObjectName("refresh2")
        self.gridLayout_6.addWidget(self.refresh2, 2, 4, 1, 1)
        self.recognition = QtWidgets.QPushButton(self.tab_7)
        self.recognition.setStyleSheet("background-color: rgb(209, 209, 104);")
        self.recognition.setObjectName("recognition")
        self.gridLayout_6.addWidget(self.recognition, 3, 4, 1, 1)
        self.load_class_path = QtWidgets.QLineEdit(self.tab_7)
        self.load_class_path.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.load_class_path.setObjectName("load_class_path")
        self.gridLayout_6.addWidget(self.load_class_path, 1, 3, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_6, 4, 5, 1, 1)
        self.label_img_show = QtWidgets.QLabel(self.tab_7)
        self.label_img_show.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_img_show.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_img_show.setText("")
        self.label_img_show.setObjectName("label_img_show")
        self.gridLayout_5.addWidget(self.label_img_show, 2, 5, 2, 1)
        self.tabWidget_info_show.addTab(self.tab_7, "")
        self.gridLayout_3.addWidget(self.tabWidget_info_show, 2, 1, 1, 1)
        self.tabWidget_oper = QtWidgets.QTabWidget(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tabWidget_oper.setFont(font)
        self.tabWidget_oper.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabWidget_oper.setStyleSheet("background-color: rgb(124, 221, 215);\n"
"font: 12pt \"Times New Roman\";")
        self.tabWidget_oper.setObjectName("tabWidget_oper")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.te_screen_display = QtWidgets.QTextEdit(self.tab_6)
        self.te_screen_display.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.te_screen_display.setObjectName("te_screen_display")
        self.gridLayout_4.addWidget(self.te_screen_display, 3, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.load_xml_path = QtWidgets.QPushButton(self.tab_6)
        self.load_xml_path.setStyleSheet("background-color: rgb(175, 177, 255);")
        self.load_xml_path.setObjectName("load_xml_path")
        self.gridLayout.addWidget(self.load_xml_path, 1, 0, 1, 1)
        self.load_train_pic_path = QtWidgets.QLineEdit(self.tab_6)
        self.load_train_pic_path.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.load_train_pic_path.setObjectName("load_train_pic_path")
        self.gridLayout.addWidget(self.load_train_pic_path, 0, 1, 1, 1)
        self.load_xml_path_2 = QtWidgets.QLineEdit(self.tab_6)
        self.load_xml_path_2.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.load_xml_path_2.setObjectName("load_xml_path_2")
        self.gridLayout.addWidget(self.load_xml_path_2, 1, 1, 1, 1)
        self.pb_data_input_path = QtWidgets.QPushButton(self.tab_6)
        self.pb_data_input_path.setStyleSheet("background-color: rgb(175, 177, 255);")
        self.pb_data_input_path.setObjectName("pb_data_input_path")
        self.gridLayout.addWidget(self.pb_data_input_path, 2, 0, 1, 1)
        self.le_data_input_path = QtWidgets.QLineEdit(self.tab_6)
        self.le_data_input_path.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.le_data_input_path.setObjectName("le_data_input_path")
        self.gridLayout.addWidget(self.le_data_input_path, 2, 1, 1, 1)
        self.load_train_path = QtWidgets.QPushButton(self.tab_6)
        self.load_train_path.setStyleSheet("background-color: rgb(175, 177, 255);")
        self.load_train_path.setObjectName("load_train_path")
        self.gridLayout.addWidget(self.load_train_path, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.pb_save_dir_path = QtWidgets.QPushButton(self.tab_6)
        self.pb_save_dir_path.setStyleSheet("background-color: rgb(175, 177, 255);")
        self.pb_save_dir_path.setObjectName("pb_save_dir_path")
        self.gridLayout.addWidget(self.pb_save_dir_path, 3, 0, 1, 1)
        self.le_save_dir_path = QtWidgets.QLineEdit(self.tab_6)
        self.le_save_dir_path.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.le_save_dir_path.setObjectName("le_save_dir_path")
        self.gridLayout.addWidget(self.le_save_dir_path, 3, 1, 1, 1)
        self.pb_refresh = QtWidgets.QPushButton(self.tab_6)
        self.pb_refresh.setStyleSheet("background-color: rgb(175, 177, 255);")
        self.pb_refresh.setObjectName("pb_refresh")
        self.gridLayout.addWidget(self.pb_refresh, 4, 0, 1, 1)
        self.pb_quit = QtWidgets.QPushButton(self.tab_6)
        self.pb_quit.setStyleSheet("background-color: rgb(175, 177, 255);")
        self.pb_quit.setObjectName("pb_quit")
        self.gridLayout.addWidget(self.pb_quit, 4, 2, 1, 1)
        self.pb_run = QtWidgets.QPushButton(self.tab_6)
        self.pb_run.setStyleSheet("background-color: rgb(175, 177, 255);")
        self.pb_run.setObjectName("pb_run")
        self.gridLayout.addWidget(self.pb_run, 4, 1, 1, 1)
        self.label_batch = QtWidgets.QLabel(self.tab_6)
        self.label_batch.setObjectName("label_batch")
        self.gridLayout.addWidget(self.label_batch, 2, 3, 1, 1)
        self.label_epoch = QtWidgets.QLabel(self.tab_6)
        self.label_epoch.setObjectName("label_epoch")
        self.gridLayout.addWidget(self.label_epoch, 1, 3, 1, 1)
        self.checkBox_gpu = QtWidgets.QCheckBox(self.tab_6)
        self.checkBox_gpu.setObjectName("checkBox_gpu")
        self.gridLayout.addWidget(self.checkBox_gpu, 0, 3, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_6)
        self.comboBox_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout.addWidget(self.comboBox_2, 2, 4, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.tab_6)
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 1, 4, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 2, 0, 1, 1)
        self.tabWidget_oper.addTab(self.tab_6, "")
        self.gridLayout_3.addWidget(self.tabWidget_oper, 2, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 1, 0, 1, 1)
        MainWindowv.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindowv)
        self.tabWidget_info_show.setCurrentIndex(0)
        self.tabWidget_oper.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindowv)

    def retranslateUi(self, MainWindowv):
        _translate = QtCore.QCoreApplication.translate
        MainWindowv.setWindowTitle(_translate("MainWindowv", "MainWindow"))
        self.label.setText(_translate("MainWindowv", "火种V1.0"))
        self.load_class.setText(_translate("MainWindowv", "加载类别"))
        self.recognit_pic.setText(_translate("MainWindowv", "图片"))
        self.load_model.setText(_translate("MainWindowv", "加载模型"))
        self.recognit_batch.setText(_translate("MainWindowv", "批量识别"))
        self.refresh2.setText(_translate("MainWindowv", "刷新"))
        self.recognition.setText(_translate("MainWindowv", "识别"))
        self.tabWidget_info_show.setTabText(self.tabWidget_info_show.indexOf(self.tab_7), _translate("MainWindowv", "执行显示"))
        self.load_xml_path.setText(_translate("MainWindowv", "2加载标注文件"))
        self.pb_data_input_path.setText(_translate("MainWindowv", "3选择类别文件"))
        self.load_train_path.setText(_translate("MainWindowv", "1加载训练图片"))
        self.pb_save_dir_path.setText(_translate("MainWindowv", "4模型保存路径"))
        self.pb_refresh.setText(_translate("MainWindowv", "刷新"))
        self.pb_quit.setText(_translate("MainWindowv", "退出"))
        self.pb_run.setText(_translate("MainWindowv", "训练"))
        self.label_batch.setText(_translate("MainWindowv", "Batch_Size"))
        self.label_epoch.setText(_translate("MainWindowv", "Epoch"))
        self.checkBox_gpu.setText(_translate("MainWindowv", "gpu"))
        self.comboBox_2.setItemText(0, _translate("MainWindowv", "1"))
        self.comboBox_2.setItemText(1, _translate("MainWindowv", "2"))
        self.comboBox_2.setItemText(2, _translate("MainWindowv", "4"))
        self.comboBox_2.setItemText(3, _translate("MainWindowv", "8"))
        self.comboBox_2.setItemText(4, _translate("MainWindowv", "16"))
        self.comboBox.setItemText(0, _translate("MainWindowv", "10"))
        self.comboBox.setItemText(1, _translate("MainWindowv", "50"))
        self.comboBox.setItemText(2, _translate("MainWindowv", "100"))
        self.comboBox.setItemText(3, _translate("MainWindowv", "500"))
        self.comboBox.setItemText(4, _translate("MainWindowv", "1000"))
        self.comboBox.setItemText(5, _translate("MainWindowv", "2000"))
        self.comboBox.setItemText(6, _translate("MainWindowv", "3000"))
        self.comboBox.setItemText(7, _translate("MainWindowv", "4000"))
        self.comboBox.setItemText(8, _translate("MainWindowv", "5000"))
        self.comboBox.setItemText(9, _translate("MainWindowv", "10000"))
        self.tabWidget_oper.setTabText(self.tabWidget_oper.indexOf(self.tab_6), _translate("MainWindowv", "操作窗口"))

